BUG: Crop long sample transects
We were getting this error
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
due to the input size being too big
https://github.com/pytorch/pytorch/issues/4107